name: "🎾  Record a doubles match"
description: "Log a finished doubles match – winner first"
labels: ["new-doubles-match"]
body:
  - type: input
    id: date
    attributes:
      label: Match date (YYYY-MM-DD)
      placeholder: "2025-08-05"
    validations:
      required: true
      pattern: "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"
  - type: textarea
    id: teams
    attributes:
      label: "Teams (team1, team2)"
      placeholder: |
        @github_handle1, @github_handle2 || @github_handle3, @github_handle4
    validations:
      required: true
  - type: textarea
    id: sets
    attributes:
      label: "Sets (one line per set, team1's games first)"
      description: |
        Enter as `<team1Games>-<team2Games>`, e.g.
        ```
        6-3
        4-6
        10-8
        ```
    validations:
      required: true